DROP TABLE IF EXISTS TIPSTRICKS;
DROP TABLE IF EXISTS TIPSTRICKS_CATEGORIE;
DROP TABLE IF EXISTS TRACKINGDATA;

CREATE TABLE TIPSTRICKS_CATEGORIE (
	ID INT NOT NULL AUTO_INCREMENT,
	OMSCHRIJVING VARCHAR(1000) NOT NULL,
	CONSTRAINT PK_TIPSTRICKS_CATEGORIE PRIMARY KEY(ID)
);

CREATE TABLE TIPSTRICKS (
	ID INT NOT NULL AUTO_INCREMENT,
	OMSCHRIJVING VARCHAR(1000) NOT NULL,
	GEBRUIKER_NIVEAU INT NOT NULL,
	CATEGORIE INT NOT NULL,
	CONSTRAINT PK_TIPSTRICKS PRIMARY KEY(ID),
	CONSTRAINT FK_TIPSTRICKS_CATEGORIE FOREIGN KEY(CATEGORIE) REFERENCES TIPSTRICKS_CATEGORIE(ID)
);

INSERT INTO  TIPSTRICKS_CATEGORIE VALUES (NULL, "Veiligheid");
INSERT INTO TIPSTRICKS VALUES (NULL, "Steek rustig over", 1, (SELECT ID FROM TIPSTRICKS_CATEGORIE WHERE OMSCHRIJVING = 'Veiligheid'));

CREATE TABLE TRACKINGDATA (
	ID VARCHAR(1000) NOT NULL,
	X FLOAT NOT NULL,
	Y FLOAT NOT NULL,
	BOOTNAAM VARCHAR(100),
	LAATST_BIJGEWERKT DATETIME NOT NULL,
	RICHTING FLOAT NOT NULL,
	BOOTTYPE VARCHAR(100) NOT NULL,
	NIVEAU INT NOT NULL,
	CONSTRAINT PK_TRACKINGDATA PRIMARY KEY(ID)
	CONSTRAINT UNIEK_TRACKINGDATA UNIQUE (BOOTNAAM)
);



INSERT INTO TRACKINGDATA VALUES (1, 100, 2);
INSERT INTO TRACKINGDATA VALUES (2, 200, 1.5);